CONNECT 'jdbc:derby:derbyDB;create=true';

CREATE TABLE CONTACT_INFORMATION  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	ADDRESS VARCHAR(100),
	ZIP VARCHAR(100),
	COUNTRY VARCHAR(100)
) ;

CREATE TABLE SAMPLE_COLLECTION  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	ACRONYM VARCHAR(100),
	NAME VARCHAR(100),
	DESCRIPTION CLOB(1000),
	COLLECTION_TYPE VARCHAR(100),
	CONTACT_INFORMATION VARCHAR(100),
	CONSTRAINT SAMPLE_COLLECTION_CONTACT_INFORMATION_FK FOREIGN KEY (CONTACT_INFORMATION) REFERENCES CONTACT_INFORMATION(ID)
) ;

CREATE TABLE SAMPLE  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	MATERIAL_TYPE VARCHAR(200),
	MATERIAL_TYPE_DETAILED VARCHAR(800),


	ANATOMICAL_SITE_ID VARCHAR(100),
	ANATOMICAL_SITE_TERM VARCHAR(100),
	ANATOMICAL_SITE_DESCRIPTION CLOB(1000),

	BIOBANK VARCHAR(800),

	DISEASE_ID VARCHAR(100),
	DISEASE_PREFFERED_TERM VARCHAR(200),
	DISEASE_DESCRIPTION VARCHAR(500),

	YEAR_OF_SAMPLING INT,
	YEAR_OF_BIRTH INT,
	YEAR_OF_DEATH INT,
	YEAR_OF_DIAGNOSIS INT,
	YEAR_OF_REMISSION INT,

	PROBAND VARCHAR(200),
	MUTATION VARCHAR(200),
	REGISTRY_ID VARCHAR(200),

	SEX VARCHAR(100),
	PARTICIPANT_ID VARCHAR(200),
	LAST_UPDATED DATE,
	UPLOAD_DATE DATE,

	SAMPLE_COLLECTION VARCHAR(100),
	CONSTRAINT SAMPLE_SAMPLE_COLLECTION_FK FOREIGN KEY (SAMPLE_COLLECTION) REFERENCES SAMPLE_COLLECTION(ID)
) ;
